language: python

branches:
  only:
    - master

python:
  - "2.7"
sudo: required

before_install:
  - "sudo apt-get install wireless-tools"
  - "sudo apt-get install python-netifaces"


install:
  - "sudo apt-get install python-scapy"

script: 
  - sudo python pifiltrate.py
